### ISSUE TITLE
不能记忆配置

### ISSUE THREAD

**Issue by svran** [Sunzxyong/findViewById-support#1]
之前选好的配置不能保存呐.每次使用都要去勾选一遍.
还有就是增量更新已经findViewById的控件有一定问题.

**Comment by svran** [comment]
还有就是这个选择一个方法能不能可以新建一个方法,不可能这些findview都放到onCreate中去呐,一般都是放到一个新的方法(例如:initView())中去.

**Comment by Sunzxyong** [comment]
@svran 新建方法这个是由业务方新建方法好后（如initView），再选择业务方已有的方法进行生成FindViewById，当然这个也可以提供一个接口
持久化配置和增量find这个功能会在下个月初加好，谢谢您的建议~

**Comment by KobeBryant824** [comment]
Insert Positon无法点击

**Comment by Sunzxyong** [comment]
@KobeBryant824 Insert Positon在Kotlin语言模式下是不能点击，这个是正常的

**Comment by Sunzxyong** [comment]
@svran update version at v1.4
